services:
  frontend:
    build:
      context: ./  # Root folder
    ports:
      - "5173:5173"  # Expose frontend on port 8080
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env